### ISSUE TITLE
Some committers are shown as not.committed.yet

### ISSUE THREAD

**Issue by Barlerer** [kelhaji/geit#28]
In many of the repos I try to get the statistics, I get `not.committed.yet` as an author, in this case there is people in the repo but only 1 is shown in the HTML.
![image](https://user-images.githubusercontent.com/34626564/100018537-47c84500-2de5-11eb-9fd7-fa6d87eaba28.png)

**Comment by kelhaji** [comment]
Hmm, interesting.

Which version of git are you using? What OS are you using?

**Comment by Barlerer** [comment]
I tried on Ubuntu 20.04 running on WSL2 and native Ubuntu 18.04 running on
a server

בתאריך יום ג׳, 24 בנוב׳ 2020, 02:15, מאת kelhaji ‏<notifications@github.com

**Comment by Barlerer** [comment]
Should I try to run it in a docker environment? Are there any "recommended" settings?

**Comment by kelhaji** [comment]
There is no need to run it in a docker environment, or with specific recommended settings. When pulling the repositories did you edit anything it before running Geit? 

Furthermore, do you see any user named "not.commited.yet" when running this command on the repo: `git shortlog -sne`

**Comment by Barlerer** [comment]
No, I did not change anything.
When running `git shortlog -sne` I get all of the committers, no "not.commited.yet"
